feat: added list notes and delete case commands and fix: removed unused import "timedelta"
vcokltfre/Magoji pull request #36
Opened 2021-03-04 21:32 UTC by ChiliPy

2021-03-04 21:39 UTC, ToxicKidz requested changes

2021-03-04 21:39 UTC, ToxicKidz commented on cogs/moderation/moderation.py
```suggestion
```
You already made the notes command.

2021-03-04 21:45 UTC, ChiliPy commented on cogs/moderation/moderation.py
fixed that now

2021-03-25 14:03 UTC, ToxicKidz requested changes
@ChiliPy Resolve conflicts and then it can be merged.

2021-04-23 16:23 UTC, ToxicKidz commented
This is taking too long so imma close this.

2021-04-23 16:23 UTC, closed without merging